#include "DungeonModel.h"
#include "Misc/AutomationTest.h"
#include "Kismet/GameplayStatics.h"
#if WITH_DEV_AUTOMATION_TESTS
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FDungeonPhase2,"Dungeon.Phase2.EconomyPresentation",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FDungeonPhase2::RunTest(const FString& Parameters){
 auto M=NewObject<UDungeonModel>();TestTrue(TEXT("Initialize"),M->Initialize());M->Testing=true;M->NewGame(0,false);M->Town();
 TestEqual(TEXT("100 male names"),M->MaleNames.Num(),100);TestEqual(TEXT("100 female names"),M->FemaleNames.Num(),100);TSet<FString> Names;for(auto N:M->MaleNames)Names.Add(N);TestEqual(TEXT("Unique male names"),Names.Num(),100);Names.Empty();for(auto N:M->FemaleNames)Names.Add(N);TestEqual(TEXT("Unique female names"),Names.Num(),100);
 M->Recruit(3);TestFalse(TEXT("Companion receives name"),M->State->Party[1].Name.IsEmpty());TestTrue(TEXT("Names differ"),M->State->Party[0].Name!=M->State->Party[1].Name);
 for(auto D:M->Items)if(!D.Slot.IsEmpty()){for(int32 Q=0;Q<4;++Q)TestTrue(TEXT("Every quality improves actual power"),M->ItemPower(FBagItem(D.Id,1,Q+1))>M->ItemPower(FBagItem(D.Id,1,Q)));}
 M->State->Party[1].Bag.Empty();M->AddItem(FBagItem("dagger",1,3),1);int32 Gold=M->State->Gold,Price=M->SellPrice(M->State->Party[1].Bag[0]);TestTrue(TEXT("Sell from companion bag"),M->Sell(1,0));TestEqual(TEXT("Exact sale proceeds"),M->State->Gold,Gold+Price);TestTrue(TEXT("Sale removes item"),M->State->Party[1].Bag.IsEmpty());TestFalse(TEXT("Stale sale rejected"),M->Sell(1,0));
 M->State->Gold=10000;auto& H=M->State->Party[0];int32 Attack=M->Attack(H);TestTrue(TEXT("Upgrade succeeds"),M->Upgrade(0,0));TestTrue(TEXT("Upgrade increases damage"),M->Attack(M->State->Party[0])>Attack);
 TestFalse(TEXT("Healthy party needs no healing"),M->NeedsCare("heal"));Gold=M->State->Gold;M->TownService("heal");TestEqual(TEXT("No charge for unneeded healing"),M->State->Gold,Gold);M->State->Party[1].HP=0;TestTrue(TEXT("Dead companion needs resurrection"),M->NeedsCare("resurrect"));M->TownService("resurrect");TestFalse(TEXT("Resurrection clears need"),M->NeedsCare("resurrect"));
 M->EnterFloor(0);auto Preview=M->EncounterRoster(109);auto Again=M->EncounterRoster(109);TestTrue(TEXT("Preview stable"),Preview==Again);M->TimedCombat=true;M->State->Party[0].Stats[1]=100;M->StartCombat(109);TestEqual(TEXT("Battle count equals preview"),M->Enemies.Num(),Preview.Num());for(int32 I=0;I<Preview.Num();++I)TestEqual(TEXT("Battle identities equal preview"),M->Enemies[I].Id,Preview[I]);M->Action("Defend");TestEqual(TEXT("Actions unavailable during delay"),M->Acting,-1);int32 Turn=M->Turn;M->Action("Attack");TestEqual(TEXT("Repeated click cannot act"),M->Turn,Turn);for(int32 I=0;I<30&&M->Combat&&M->Acting<0;++I)M->TickCombat(.8f);TestTrue(TEXT("Timed turn returns control or finishes"),!M->Combat||M->Acting>=0);
 for(auto& E:M->Enemies)E.HP=0;M->FinishCombat();M->Combat=false;M->State->Party[0].Bag.Empty();M->StartCombat(175,true);for(auto& E:M->Enemies)E.HP=0;Gold=M->State->Gold;M->FinishCombat();TestTrue(TEXT("Guardian awards at least 500 gold"),M->State->Gold>=Gold+500);TestTrue(TEXT("Guardian guaranteed quality equipment"),M->State->Party[0].Bag.ContainsByPredicate([](const FBagItem& B){return B.Quality>=2;}));
 M->State->X=3;M->State->Y=9;M->State->Facing=1;M->State->Floors[0].Taken.AddUnique(M->Cell(4,9));TestFalse(TEXT("Searched tile loses special prompt"),M->Context().Contains("disarm"));
 TestTrue(TEXT("History stored in save model"),M->State->History.Num()>0);return true;
}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FDungeonAstra,"Dungeon.Phase2.Astra",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FDungeonAstra::RunTest(const FString& Parameters){
 auto M=NewObject<UDungeonModel>();M->Initialize();M->Testing=true;M->NewGame(0,false);M->Recruit(3);M->Recruit(5);M->Recruit(4);M->Recruit(6);M->TimedCombat=true;
 for(int32 F=0;F<M->Floors.Num();++F)for(int32 Y=0;Y<M->Floors[F].Rows.Num();++Y){int32 X=M->Floors[F].Rows[Y].Find("A");if(X<0)continue;M->EnterFloor(F);M->State->Keys.AddUnique(M->Floors[F].Key);M->State->Bosses.AddUnique(F);for(const auto& Edge:M->State->Floors[F].Boundaries)if(Edge.Mandatory)M->OpenBoundary(Edge);M->TickDoors(1);M->State->X=X;M->State->Y=Y;M->State->Facing=1;M->Screen="Dungeon";M->Interact();TestEqual(TEXT("Standing at final threshold opens choice"),M->Screen,FString("Choice"));M->FinalChoice(false);TestEqual(TEXT("One final boss"),M->Enemies.Num(),1);if(M->Enemies.IsEmpty())return false;TestEqual(TEXT("Reject fights Astra"),M->Enemies[0].Id,FString("astra"));TestEqual(TEXT("Correct Astra artwork"),M->Enemies[0].Art,FString("final_boss"));TestTrue(TEXT("Boss encounter cannot flee"),M->BossFight);for(auto& H:M->State->Party)H.HP=10000;M->EnemyAction(0);for(auto& H:M->State->Party)TestTrue(TEXT("Cataclysm hits every companion"),H.HP<10000);M->Enemies[0].HP=0;M->FinishCombat();TestEqual(TEXT("Astra victory unlocks good ending"),M->State->Ending,1);return true;}
 AddError(TEXT("Astra tile missing"));return false;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FDungeonRefinements,"Dungeon.Phase2.Refinements",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FDungeonRefinements::RunTest(const FString& Parameters){
 auto M=NewObject<UDungeonModel>();M->Initialize();M->Testing=true;M->NewGame(0,false);M->Recruit(4);M->Recruit(3);M->EnterFloor(0);auto& D=M->Floors[0];int32 Exit=-1,Boss=-1;
 for(int32 Y=0;Y<D.Rows.Num();++Y)for(int32 X=0;X<D.Rows[Y].Len();++X){if(D.Rows[Y][X]=='>')Exit=M->Cell(X,Y);if(D.Rows[Y][X]=='B')Boss=M->Cell(X,Y);}
 TestTrue(TEXT("Guardian and key required"),!M->CanDescend());M->State->Keys.AddUnique(D.Key);M->State->Bosses.AddUnique(0);TestFalse(TEXT("Boss flag alone cannot bypass living guardian"),M->CanDescend());M->State->Keys.Empty();M->State->Floors[0].Defeated.Add(Boss,0);TestFalse(TEXT("Guardian alone does not unlock exit"),M->CanDescend());M->State->X=Exit%D.Rows[0].Len();M->State->Y=Exit/D.Rows[0].Len();M->Interact();TestEqual(TEXT("Standing at stairs cannot bypass key"),M->State->Floor,0);M->State->Keys.AddUnique(D.Key);for(const auto& Edge:M->State->Floors[0].Boundaries)if(Edge.Mandatory)M->OpenBoundary(Edge);M->TickDoors(1);TestTrue(TEXT("Guardian plus physically opened gate unlock exit"),M->CanDescend());
 TSet<FString> Loot;bool Armor=false;for(int32 I=0;I<100;++I){auto B=M->EquipmentLoot(2);Loot.Add(B.Id);Armor|=M->Item(B.Id)->Slot!="Weapon";}TestTrue(TEXT("Loot includes many equipment types"),Loot.Num()>5&&Armor);
 for(const auto& Skill:M->Skills)if(Skill.Power>0&&(Skill.Target=="enemy"||Skill.Target=="all")){auto H=M->State->Party[0];int32 Before=M->SkillDamage(H,Skill);H.Stats[0]+=40;TestTrue(TEXT("Damaging specials scale with attack"),M->SkillDamage(H,Skill)>Before);}
 M->State->Floor=0;M->TimedCombat=true;M->StartCombat(109);M->State->Party[1].Level=20;M->State->Party[1].MP=100;M->Acting=1;M->TurnDelay=0;M->PendingEnemy=-1;auto E=M->Enemies[0];E.HP=E.MaxHP=10000;M->Enemies.Init(E,3);M->Action("Skill",2);for(auto Enemy:M->Enemies)TestTrue(TEXT("Grenade damages all enemies"),Enemy.HP<10000);TestTrue(TEXT("Grenade cue queued"),M->CombatCues.Contains("grenade"));M->Combat=false;
 M->WorldDirty=false;M->Recruit(5);TestTrue(TEXT("Recruitment refreshes world"),M->WorldDirty);
 auto Original=M->Floors[0].Rows;M->State->RandomSeed+=104729;M->RandomizeLayouts();FString LayoutError;TestTrue(TEXT("Regenerated layout validates"),M->ValidateFloor(0,LayoutError));TestTrue(TEXT("Map stored in save"),M->Floors[0].Rows==M->State->Floors[0].Layout);for(int32 F=0;F<M->Floors.Num();++F){M->State->Floor=F;const auto& Rows=M->Floors[F].Rows;for(TCHAR Tile: {TCHAR('S'),TCHAR('K'),TCHAR('B'),TCHAR('>'),TCHAR('A')}){int32 Before=0,After=0;for(auto Row:M->BaseFloors[F].Rows)for(auto C:Row)Before+=C==Tile;for(auto Row:Rows)for(auto C:Row)After+=C==Tile;TestEqual(TEXT("Randomization preserves objectives"),After,Before);}}
 M->EnterFloor(0);M->Testing=false;M->Screen="Dungeon";FString Slot="LayoutTest_"+FGuid::NewGuid().ToString(EGuidFormats::Digits);auto Expected=M->Floors[0].Rows;TestTrue(TEXT("Random layout save"),M->Save(Slot));auto Restored=NewObject<UDungeonModel>();Restored->Initialize();TestTrue(TEXT("Random layout load"),Restored->Load(Slot));TestTrue(TEXT("Layout stable after load"),Restored->Floors[0].Rows==Expected);UGameplayStatics::DeleteGameInSlot("Lonemoore_"+Slot,0);return true;
}

#endif

