"""Import only Phase 2 material; leave original artwork and geometry untouched."""
import unreal as u
tools=u.AssetToolsHelpers.get_asset_tools()
m=u.load_asset('/Game/Game/Materials/M_Key') or tools.create_asset('M_Key','/Game/Game/Materials',u.Material,u.MaterialFactoryNew())
u.MaterialEditingLibrary.delete_all_material_expressions(m)
m.set_editor_property('two_sided',True)
m.set_editor_property('blend_mode',u.BlendMode.BLEND_MASKED)
m.set_editor_property('opacity_mask_clip_value',.035)
m.set_editor_property('shading_model',u.MaterialShadingModel.MSM_UNLIT)
def node(cls):return u.MaterialEditingLibrary.create_material_expression(m,cls,0,0)
uv=node(u.MaterialExpressionTextureCoordinate)
scale=node(u.MaterialExpressionMultiply)
scale.set_editor_property('const_b',1.0)
xy=node(u.MaterialExpressionConstant2Vector);xy.set_editor_property('r',.2);xy.set_editor_property('g',.68)
u.MaterialEditingLibrary.connect_material_expressions(uv,'',scale,'A');u.MaterialEditingLibrary.connect_material_expressions(xy,'',scale,'B')
col=node(u.MaterialExpressionScalarParameter);col.set_editor_property('parameter_name','Column');col.set_editor_property('default_value',0)
zero=node(u.MaterialExpressionConstant);zero.set_editor_property('r',0)
offset=node(u.MaterialExpressionAppendVector)
u.MaterialEditingLibrary.connect_material_expressions(col,'',offset,'A');u.MaterialEditingLibrary.connect_material_expressions(zero,'',offset,'B')
add=node(u.MaterialExpressionAdd)
u.MaterialEditingLibrary.connect_material_expressions(scale,'',add,'A');u.MaterialEditingLibrary.connect_material_expressions(offset,'',add,'B')
tex=node(u.MaterialExpressionTextureSampleParameter2D);tex.set_editor_property('parameter_name','Portrait');tex.set_editor_property('texture',u.load_asset('/Game/Game/ImportedArt/T_keys'))
u.MaterialEditingLibrary.connect_material_expressions(add,'',tex,'UVs')
u.MaterialEditingLibrary.connect_material_property(tex,'RGB',u.MaterialProperty.MP_EMISSIVE_COLOR)
u.MaterialEditingLibrary.connect_material_property(tex,'R',u.MaterialProperty.MP_OPACITY_MASK)
u.MaterialEditingLibrary.recompile_material(m);u.EditorAssetLibrary.save_loaded_asset(m)
print('PHASE2_KEY_MATERIAL_COMPLETE')
for name in ['Stone','Wood','Metal']:
    material=u.load_asset('/Game/Game/Materials/M_'+name)
    material.set_editor_property('used_with_instanced_static_meshes',True)
    u.MaterialEditingLibrary.recompile_material(material)
    u.EditorAssetLibrary.save_loaded_asset(material)
