from pathlib import Path
r=Path(__file__).resolve().parents[1]/'Source/DungeonCrawler'
p=r/'DungeonTests.cpp';s=p.read_text();a=s.index(' int32 StartX=');b=s.index(' int32 Seen=',a)
s=s[:a]+''' int32 StartX=M->State->X;TestTrue(TEXT("Forward step succeeds"),M->Move(1));TestEqual(TEXT("One grid step"),M->State->X,StartX+1);for(int32 I=0;I<4;++I)M->Rotate(1);TestEqual(TEXT("Four turns preserve facing"),M->State->Facing,1);
 auto Wall=M->State->Floors[0].Boundaries.FindByPredicate([](const FDungeonBoundary& E){return E.Kind=="Wall"&&E.B>=0;});int W=M->Floors[0].Rows[0].Len();
 auto Face=[&](int A,int B){M->State->X=A%W;M->State->Y=A/W;M->State->Facing=B%W>A%W?1:B%W<A%W?3:B/W>A/W?2:0;};
 if(Wall){Face(Wall->A,Wall->B);TestFalse(TEXT("Wall blocks movement"),M->Move(1));}
 auto Gate=M->State->Floors[0].Boundaries.FindByPredicate([](const FDungeonBoundary& E){return E.Mandatory;});if(Gate){Face(Gate->A,Gate->B);M->Interact();TestFalse(TEXT("Missing key leaves lock closed"),M->CanCross(0,Gate->A,Gate->B));M->State->Keys.Add(M->Floors[0].Key);M->Interact();M->TickDoors(1);TestTrue(TEXT("Matching key and completed opening permits passage"),M->CanCross(0,Gate->A,Gate->B));}
'''+s[b:]
s=s.replace("if(T=='#'||Parent.Contains(N))continue;if(T=='D'&&!M->Walkable(X,Y)&&!S->Keys.Contains(D.Key))continue;if(T=='G'&&!M->Walkable(X,Y))continue;",'const auto* Edge=M->Boundary(S->Floor,C,N);if(T==\'#\'||Parent.Contains(N)||!Edge||Edge->Kind=="Wall")continue;if(!M->CanCross(S->Floor,C,N)&&!M->HasRequirement(S->Floor,*Edge))continue;')
s=s.replace("if(T=='D'||T=='+'||T=='?'||T=='T')M->Interact();",'if(!M->CanCross(S->Floor,M->Cell(S->X,S->Y),C)){M->Interact();M->TickDoors(1);}if(T==\'T\')M->Interact();');s=s.replace("if(T=='K'||T=='C'||T=='$'||T=='!'||T=='L')M->Interact();", "if(T=='K'||T=='C'||T=='$'||T=='!'||T=='L'){M->Interact();M->TickDoors(1);}");p.write_text(s)
p=r/'DungeonPhase2Tests.cpp';s=p.read_text().replace('TestTrue(TEXT("Both requirements unlock exit"),M->CanDescend());','for(const auto& Edge:M->State->Floors[0].Boundaries)if(Edge.Mandatory)M->OpenBoundary(Edge);M->TickDoors(1);TestTrue(TEXT("Guardian plus physically opened gate unlock exit"),M->CanDescend());');s=s.replace('auto Original=M->Floors[0].Rows;M->RandomizeLayouts();TestTrue(TEXT("New map varies"),M->Floors[0].Rows!=Original);','auto Original=M->Floors[0].Rows;M->State->RandomSeed+=104729;M->RandomizeLayouts();FString LayoutError;TestTrue(TEXT("Regenerated layout validates"),M->ValidateFloor(0,LayoutError));');s=s.replace('M->Testing=false;M->Screen="Dungeon";FString Slot="LayoutTest_', 'M->EnterFloor(0);M->Testing=false;M->Screen="Dungeon";FString Slot="LayoutTest_');p.write_text(s)
