"""Read-only verification of the current RoomKit polish preservation baseline.

Only Saved/RoomKitPolish/preservation.json is written. No protected file is
created, restored or rewritten, including when verification fails.
"""
import hashlib
import json
import re
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
EVIDENCE = ROOT / "Saved/RoomKitPolish"
BASELINE = EVIDENCE / "protected_before.json"
# These four exact paths are outputs of the performance automation suite, not
# player save slots. All other baseline entries remain strictly protected.
GENERATED_FIXTURES = {
    "Saved/PerformancePass/Fixtures/Floor_00.sav",
    "Saved/PerformancePass/Fixtures/Floor_02.sav",
    "Saved/PerformancePass/Fixtures/Floor_16.sav",
    "Saved/PerformancePass/Fixtures/Explored.sav",
}
GENERATOR = ROOT / "Source/DungeonCrawler/DungeonPerformanceTests.cpp"


def sha256(path):
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest().upper()


def main():
    records = []
    generated = []
    errors = []
    baseline_hash = None
    try:
        generator_text = GENERATOR.read_text(encoding="utf-8-sig")
        for evidence in (
            '"Dungeon.Performance.IdenticalSceneFixtures"',
            "for(int F:{0,2,16})",
            'FString::Printf(TEXT("PerformancePass/Fixtures/Floor_%02d.sav"),F)',
            "FFileHelper::SaveArrayToFile(Data,*Path)",
            'FFileHelper::SaveArrayToFile(Data,*(FPaths::ProjectSavedDir()/TEXT("PerformancePass/Fixtures/Explored.sav")))',
        ):
            if evidence not in generator_text:
                raise ValueError("Performance fixture generator changed; review the four-path exception provenance.")
        generator_hash = sha256(GENERATOR)
        baseline_hash = sha256(BASELINE)
        before = json.loads(BASELINE.read_text(encoding="utf-8-sig"))
        if not isinstance(before, list) or len(before) != 149:
            raise ValueError("Expected the current 149-file polish baseline; do not substitute the older room-kit baseline.")
        seen = set()
        for entry in before:
            relative = entry["Path"].replace("\\", "/")
            path = ROOT / relative
            if path.is_absolute() and not path.resolve().is_relative_to(ROOT):
                raise ValueError(f"Protected path escapes the project: {relative}")
            if relative.startswith("/") or ":" in relative or ".." in Path(relative).parts:
                raise ValueError(f"Invalid protected relative path: {relative}")
            if relative.casefold() in seen:
                raise ValueError(f"Duplicate protected path: {relative}")
            seen.add(relative.casefold())
            expected = entry["SHA256"].upper()
            if not re.fullmatch(r"[0-9A-F]{64}", expected) or not isinstance(entry["Length"], int) or entry["Length"] < 0:
                raise ValueError(f"Invalid baseline metadata: {relative}")
            item = {"path": relative, "unchanged": False, "expectedSha256": expected}
            try:
                if not path.is_file():
                    item["reason"] = "missing"
                else:
                    item["length"] = path.stat().st_size
                    item["sha256"] = sha256(path)
                    item["unchanged"] = item["length"] == entry["Length"] and item["sha256"] == expected
                    if not item["unchanged"]:
                        item["reason"] = "length or SHA256 changed"
            except OSError as exc:
                item["reason"] = str(exc)
            if relative in GENERATED_FIXTURES:
                item["baselineSha256"] = item.pop("expectedSha256")
                item["baselineLength"] = entry["Length"]
                item["currentSha256"] = item.pop("sha256", None)
                item["currentLength"] = item.pop("length", None)
                item["classification"] = "autogenerated performance fixture; excluded from strict player-data preservation"
                item["provenance"] = {
                    "source": str(GENERATOR.relative_to(ROOT)).replace("\\", "/"),
                    "sourceSha256": generator_hash,
                    "test": "Dungeon.Performance.IdenticalSceneFixtures",
                    "lineStart": 24 if relative.endswith("/Explored.sav") else 13,
                    "lineEnd": 30 if relative.endswith("/Explored.sav") else 22,
                    "operation": "SaveGameToMemory then SaveArrayToFile under ProjectSavedDir/PerformancePass/Fixtures",
                }
                generated.append(item)
                if item["currentSha256"] is None:
                    errors.append(f"Generated fixture cannot be read for evidence: {relative}")
            else:
                records.append(item)
        if {item["path"] for item in generated} != GENERATED_FIXTURES:
            errors.append("The immutable baseline does not contain exactly the four documented generated fixtures.")
        if sha256(BASELINE) != baseline_hash:
            errors.append("Preservation baseline changed during verification.")
    except (OSError, ValueError, KeyError, TypeError, AttributeError) as exc:
        errors.append(str(exc))
    unchanged = sum(item["unchanged"] for item in records)
    report = {
        "status": "PASS" if not errors and len(records) == 145 and unchanged == 145 and len(generated) == 4 else "FAIL",
        "baseline": str(BASELINE.relative_to(ROOT)),
        "baselineSha256": baseline_hash,
        "protected": len(records),
        "unchanged": unchanged,
        "baselineRows": len(records) + len(generated),
        "generatedFixtureCount": len(generated),
        "generatedFixtures": generated,
        "errors": errors,
        "files": records,
        "checkedUtc": datetime.now(timezone.utc).isoformat(),
    }
    (EVIDENCE / "preservation.json").write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(json.dumps({key: value for key, value in report.items() if key not in {"files", "generatedFixtures"}}))
    return 0 if report["status"] == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
